[env:ceiling_light_4]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
build_flags = -DCORE_DEBUG_LEVEL=3
