server:
  port: 2010

spring:
  cloud:
    gateway:
      routes:
        - id: aiot-system
          uri: lb://aiot-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: aiot-device
          uri: lb://aiot-device
          predicates:
            - Path=/device/**,/board/**
      # 网关全局跨域配置
      globalcors:
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"     #设置允许跨域的来源
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60s #连接空闲超过N(s秒、ms毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      lettuce:
        pool:
          max-active: 8  #允许最大连接数
          max-idle: 8    #最大空闲连接数, 默认8
          min-idle: 0    #最小空闲连接数
          max-wait: 5s   #请求获取连接等待时间

security:
  ignore:
    whites:
      - /**/login
      - /**/code
      - /**/register

jwt:
  secret: zxcvbnmasdfghjuiyreqtuiwg